Validate search
odpi/egeria-ui-core pull request #94
Opened 2022-10-31 14:47 UTC by marius-patrascu

Added validation for the search on home page

2022-11-03 12:32 UTC, sarbull requested changes

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +    if (event.key === 'Enter') {
```js
// check if user input is valid before redirect with invalid input
if (event.key === 'Enter' && (q.isValid && types.isValid)) {
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +  const [types, setTypes]: [any, any] = useState({value: [], isPristine: true});
use same pattern
```js
{ value: [], isPristine: true, isValid: false }
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +  const [q, setQ]: [any, any] = useState({value: '', isPristine: true});
use same pattern
```js
{ value: '', isPristine: true, isValid: false }
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +                 onChange={(value: any) => setTypes({value: [...value]})}
use same pattern
```js
onChange={(value: any) => setTypes({
  value: [...value],
  isPristine: false,
  isValid: !isArrayEmpty([...value])
}
)}
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +               onChange={(event: any) => setQ({value: event.currentTarget.value})}
use same pattern
```js
onChange={(value: any) => setQ({
  value: event.currentTarget.value,
  isPristine: false,
  isValid: !isStringLonger(event.currentTarget.value, QUERY_MIN_LENGTH)
}
)}
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +               error={!q.isPristine && !isStringLonger(q.value, QUERY_MIN_LENGTH) ? 'Query must be at least ' + QUERY_MIN_LENGTH + ' characters' : ''}
```js
error={ !(!q.isPristine && q.isValid) ? `Query must be at least ${QUERY_MIN_LENGTH} characters' : ''}
```

2022-11-03 12:32 UTC, sarbull commented on src/components/MainSearch/index.tsx
> +                 error={!types.isPristine && isArrayEmpty(types.value) ? 'At least one type has to be selected' : ''}
```js
error={ !(!types.isPristine && types.isValid) ? 'At least one type has to be selected' : ''}
```

2022-11-03 13:16 UTC, marius-patrascu commented on dist/esm/components/About/index.js
> +import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
is removed

2022-11-03 13:16 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +    if (event.key === 'Enter') {
done

2022-11-03 13:16 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +  const [q, setQ]: [any, any] = useState({value: '', isPristine: true});
done

2022-11-03 13:16 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +                 onChange={(value: any) => setTypes({value: [...value]})}
done

2022-11-03 13:16 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +               onChange={(event: any) => setQ({value: event.currentTarget.value})}
done

2022-11-03 13:17 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +               error={!q.isPristine && !isStringLonger(q.value, QUERY_MIN_LENGTH) ? 'Query must be at least ' + QUERY_MIN_LENGTH + ' characters' : ''}
done

2022-11-03 13:17 UTC, marius-patrascu commented on src/components/MainSearch/index.tsx
> +                 error={!types.isPristine && isArrayEmpty(types.value) ? 'At least one type has to be selected' : ''}
done

2022-11-04 09:00 UTC, sarbull approved these changes

2022-11-04 09:05 UTC, merged